import React,{useState,useEffect,useRef} from 'react';
import {BookOpen,LayoutDashboard,Sparkles,ClipboardList,BarChart3,ShieldCheck,LogOut,ChevronRight,Menu,FileText,Gauge,TrendingUp,UserCheck} from 'lucide-react';
import {api} from './api';
import {Notify,Toast} from './ui';
import {PasswordDialog,Login} from './auth';
import {Exams} from './exam';
import {Bank,AIPage} from './bank';
import {Home,Results,Statistics,Analysis,Profile} from './reports';
import {Admin,ReviewQueue} from './admin';
import {createRoot} from 'react-dom/client';
import './style.css';
function App(){const [user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[passwordOpen,setPasswordOpen]=useState(false),[page,setPage]=useState('Trang chủ'),[mobile,setMobile]=useState(false),[toast,setToast]=useState<any>(null);const timeout=useRef<any>(null);function notify(text:string,error=false){setToast({text,error});clearTimeout(timeout.current);timeout.current=setTimeout(()=>setToast(null),6500)}useEffect(()=>{if(sessionStorage.getItem('token'))api('/me').then(setUser).catch(()=>sessionStorage.removeItem('token')).finally(()=>setLoading(false));else setLoading(false);const expired=()=>{setUser(null);notify('Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.',true)};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[]);const navigate=(p:string)=>{setPage(p);setMobile(false)};const logout=()=>{sessionStorage.removeItem('token');setUser(null);setPage('Trang chủ');setMobile(false);notify('Đã đăng xuất tài khoản.');};const items=[['Trang chủ',LayoutDashboard],['Ngân hàng câu hỏi',BookOpen],['Trợ lý AI',Sparkles],['Tạo đề kiểm tra',ClipboardList],['Kết quả kiểm tra',FileText],['Thống kê',BarChart3],['Phân tích câu hỏi',Gauge],['Thẩm định',UserCheck],['Hồ sơ học tập',TrendingUp],['Quản trị',ShieldCheck]] as const;
if(loading)return <div className="loading">Đang mở hệ thống…</div>;return <Notify.Provider value={notify}>{!user?<Login onLogin={u=>{setUser(u);setPage('Trang chủ')}}/>:<div className="app"><aside className={mobile?'open':''}><div className="brand"><div className="seal">★</div><div>PHẦN MỀM AI ỨNG DỤNG<small>NGÂN HÀNG ĐỀ THI<br/>VÀ ĐÁP ÁN</small></div></div><div className="nav-caption">KHÔNG GIAN LÀM VIỆC</div><nav>{items.filter(([p])=>p==='Quản trị'?user.role==='ADMIN':user.role==='STUDENT'?!['Ngân hàng câu hỏi','Trợ lý AI','Phân tích câu hỏi','Thẩm định'].includes(p):true).map(([p,Icon])=><button key={p} className={page===p?'active':''} onClick={()=>navigate(p)}><Icon size={19}/>{p==='Tạo đề kiểm tra'&&user.role==='STUDENT'?'Đề kiểm tra':p}{p==='Trợ lý AI'&&<span className="ai-label">AI</span>}</button>)}</nav><div className="aside-bottom"><div className="unit-note"><ShieldCheck size={20}/><span>Khoa học • Chính xác<br/>Thiết thực • Hiệu quả</span></div><div className="account"><div className="avatar">{user.name.charAt(0)}</div><div><strong>{user.name}</strong><small>{{ADMIN:'Quản trị viên',TEACHER:'Cán bộ / Giáo viên',STUDENT:'Học viên'}[user.role as string]}</small></div></div><button className="logout-button" onClick={logout}><LogOut size={18}/>Đăng xuất</button></div></aside><div className="main-shell"><header><div className="breadcrumb"><button className="icon mobile-menu" aria-label="Mở menu" onClick={()=>setMobile(!mobile)}><Menu/></button><span>Giáo dục chính trị</span><ChevronRight size={15}/><strong>{page}</strong></div><div className="header-actions"><button onClick={()=>setPasswordOpen(true)}>Đổi mật khẩu</button><span className="header-date">{new Date().toLocaleDateString('vi-VN')}</span><button className="header-logout" onClick={logout}><LogOut size={17}/>Đăng xuất</button></div></header><main key={page}>{page==='Trang chủ'?<Home user={user} go={navigate}/>:page==='Ngân hàng câu hỏi'?<Bank user={user}/>:page==='Trợ lý AI'?<AIPage/>:page==='Tạo đề kiểm tra'?<Exams user={user}/>:page==='Kết quả kiểm tra'?<Results user={user}/>:page==='Thống kê'?<Statistics/>:page==='Phân tích câu hỏi'?<Analysis/>:page==='Thẩm định'?<ReviewQueue user={user}/>:page==='Hồ sơ học tập'?<Profile user={user}/>:<Admin/>}</main><footer>PHẦN MỀM AI ỨNG DỤNG NGÂN HÀNG ĐỀ THI VÀ ĐÁP ÁN <span>Ứng dụng AI trong giáo dục chính trị</span></footer></div></div>}{passwordOpen&&<PasswordDialog onClose={()=>setPasswordOpen(false)} onChanged={()=>{sessionStorage.removeItem('token');setUser(null);setMobile(false);setPage('Trang chủ')}}/>}{toast&&<Toast toast={toast} close={()=>setToast(null)}/>}</Notify.Provider>}
createRoot(document.getElementById('root')!).render(<App/>);
