import {useState} from 'react';
import {api,levels,audiences,typeNames} from './api';
type Row={line:number,question:any,errors:string[],warnings:string[]};
export function ImportQuestions({onSaved,notify}:{onSaved:()=>void,notify:(s:string,error?:boolean)=>void}){
 const [file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<number[]>([]),[defaults,setDefaults]=useState({topic:'',level:levels[0],audience:'Cán bộ'});
 const reset=()=>{setRows([]);setSelected([])};
 async function preview(){if(!file)return;setBusy(true);reset();try{
  if(file.size>5*1024*1024)throw new Error('File tối đa 5 MB.');
  const data=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=()=>reject(new Error('Không đọc được file.'));r.readAsDataURL(file)});
  const d=await api('/questions/import/preview','POST',{filename:file.name,data,defaults});setRows(d.rows);setSelected(d.rows.filter((r:Row)=>!r.errors.length&&!r.warnings.length).map((r:Row)=>r.line));
 }catch(e:any){notify(e.message,true)}finally{setBusy(false)}}
 function template(){const csv='\uFEFFNội dung câu hỏi,Phương án A,Phương án B,Phương án C,Phương án D,Đáp án,Chủ đề,Mức độ,Đối tượng,Giải thích,Nguồn\r\nQuân đội nhân dân Việt Nam được thành lập ngày nào?,22/12/1944,19/8/1945,2/9/1945,30/4/1975,A,Truyền thống Quân đội nhân dân Việt Nam,Nhận biết,Học viên,,\r\n';const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='mau-nhap-cau-hoi.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section><p>Nhập .docx, .xlsx hoặc CSV UTF-8, tối đa 5 MB / 500 câu. Với Word: mỗi câu bắt đầu bằng “Câu 1.”, phương án ghi “A.”, “B.”…, đáp án ghi “Đáp án: A”, hướng dẫn chấm ghi “Giải thích:”. Với Excel/CSV: hàng đầu là tiêu đề cột. Hỗ trợ file Excel 200 câu Hội thi Bí thư Chi bộ và file xuất từ ngân hàng.</p><button onClick={template}>Tải CSV mẫu</button><p className="muted">Đáp án ghi A hoặc A, C. Giải thích và nguồn tài liệu không bắt buộc. File thiếu chủ đề, mức độ hoặc đối tượng sẽ dùng giá trị bên dưới.</p>
 <fieldset disabled={busy} style={{border:0,padding:0}}><label className="field"><span>Chọn file Word / Excel / CSV</span><input type="file" accept=".docx,.xlsx,.csv" onChange={e=>{setFile(e.target.files?.[0]||null);reset()}}/></label>
 <label className="field"><span>Chủ đề mặc định</span><input value={defaults.topic} maxLength={200} placeholder="Ví dụ: Hội thi Bí thư Chi bộ năm 2026" onChange={e=>{setDefaults({...defaults,topic:e.target.value});reset()}}/></label>
 <div className="form-grid">{(['level','audience'] as const).map(k=><label className="field" key={k}><span>{k==='level'?'Mức độ mặc định':'Đối tượng mặc định'}</span><select value={defaults[k]} onChange={e=>{setDefaults({...defaults,[k]:e.target.value});reset()}}>{(k==='level'?levels:audiences).map(v=><option key={v}>{v}</option>)}</select></label>)}</div>
 <button disabled={!file||defaults.topic.trim().length<2} onClick={preview}>{busy?'Đang xử lý…':'Đọc file và xem trước'}</button></fieldset>
 {!!rows.length&&<><p><strong>{rows.length} câu · {rows.filter(r=>r.errors.length).length} dòng lỗi · Đã chọn {selected.length} câu</strong></p><p className="muted">Các dòng có cảnh báo chưa được chọn sẵn. Kiểm tra rồi tích chọn từng dòng để xác nhận.</p><button disabled={busy} onClick={()=>setSelected(rows.filter(r=>!r.errors.length&&!r.warnings.length).map(r=>r.line))}>Chọn các dòng không có cảnh báo</button> <button disabled={busy} onClick={()=>setSelected([])}>Bỏ chọn tất cả</button>
 <div className="table-wrap" style={{maxHeight:420,overflow:'auto'}}><table><thead><tr><th>Nhập</th><th>Dòng</th><th>Câu hỏi / Phương án</th><th>Đáp án / Kiểm tra</th></tr></thead><tbody>{rows.map(r=><tr key={r.line}><td><input type="checkbox" aria-label={'Chọn dòng '+r.line} disabled={busy||!!r.errors.length} checked={selected.includes(r.line)} onChange={e=>setSelected(e.target.checked?[...selected,r.line]:selected.filter(i=>i!==r.line))}/></td><td>{r.line}</td><td style={{minWidth:280}}><strong>{r.question.content}</strong>{r.question.options.map((o:string,i:number)=><p key={i}>{String.fromCharCode(65+i)}. {o}</p>)}<small>{r.question.topic} · {r.question.level} · {r.question.audience}</small></td><td style={{minWidth:180}}><strong>{r.question.correct.map((i:number)=>String.fromCharCode(65+i)).join(', ')}</strong><p>{typeNames[r.question.type]}</p>{r.errors.map((e,i)=><p className="danger" key={i}>{e}</p>)}{r.warnings.map((w,i)=><p key={i}>{w}</p>)}</td></tr>)}</tbody></table></div>
 <div className="modal-actions"><button className="primary" disabled={busy||!selected.length} onClick={async()=>{setBusy(true);try{const d=await api('/questions/import','POST',rows.filter(r=>selected.includes(r.line)).map(r=>r.question));reset();notify(`Đã nhập ${d.count} câu hỏi vào ngân hàng.`);onSaved()}catch(e:any){notify(e.message,true)}finally{setBusy(false)}}}>{busy?'Đang lưu…':`Lưu ${selected.length} câu đã chọn`}</button></div></>}
 </section>
}
