import React,{useEffect,useRef,createContext} from 'react';
import {BookOpen,ClipboardList,CheckCircle2,X,GraduationCap} from 'lucide-react';
import {levels,audiences,topics,typeNames,Question} from './api';
export const Notify=createContext<(s:string,error?:boolean)=>void>(()=>{});
// An logo neu file anh chua duoc dat vao client/public
export const hideLogo=(e:React.SyntheticEvent<HTMLImageElement>)=>{e.currentTarget.style.display='none'};
export function Field({label,children}:{label:string,children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
export function Select({value,onChange,items,all}:{value:string,onChange:(v:string)=>void,items:string[],all?:string}){return <select value={value} onChange={e=>onChange(e.target.value)}>{all&&<option value="">{all}</option>}{items.map(v=><option key={v}>{v}</option>)}</select>}
export function Badge({children,tone=''}:{children:React.ReactNode,tone?:string}){return <span className={'badge '+tone}>{children}</span>}
export function Modal({title,children,onClose}:{title:string,children:React.ReactNode,onClose:()=>void}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();return()=>ref.current?.close()},[]);return <dialog ref={ref} onCancel={onClose}><div className="modal-head"><h2>{title}</h2><button className="icon" aria-label="Đóng" onClick={onClose}><X size={21}/></button></div><div className="modal-body">{children}</div></dialog>}
export function Empty({text='Chưa có dữ liệu.'}:{text?:string}){return <div className="empty"><BookOpen size={34}/><p>{text}</p></div>}
export function RecoveryCode({code}:{code:string}){return <div className="note"><div><strong>Lưu mã khôi phục mới</strong><p>Mã chỉ hiển thị lần này. Cất giữ riêng để đặt lại mật khẩu khi quên; mã cũ đã hết hiệu lực.</p><input aria-label="Mã khôi phục" readOnly value={code} onFocus={e=>e.target.select()} style={{marginTop:12,fontFamily:'monospace'}}/></div></div>}
export function Toast({toast,close}:{toast:any,close:()=>void}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current;if(el&&typeof el.showPopover==='function'){el.hidePopover();el.showPopover()}},[toast]);return <div ref={ref} popover="manual" role="alert" className={'toast '+(toast.error?'error':'')}><CheckCircle2 size={20}/><span>{toast.text}</span><button className="icon" aria-label="Đóng thông báo" onClick={close}><X size={18}/></button></div>}
export function Title({eyebrow,title,sub,action}:{eyebrow?:string,title:string,sub?:string,action?:React.ReactNode}){return <div className="page-title"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{sub&&<p className="muted">{sub}</p>}</div>{action}</div>}
export function StatCards({data}:{data:any}){return <div className="stats-grid">{[[BookOpen,'Câu hỏi trong ngân hàng',data.questions,'red'],[ClipboardList,'Đề kiểm tra',data.exams,'olive'],[GraduationCap,'Điểm trung bình',data.average===null?'—':data.average?.toFixed(2)+'/10','gold'],[CheckCircle2,'Tỷ lệ đạt',data.passRate===null?'—':data.passRate?.toFixed(0)+'%','green']].map(([Icon,label,v,color]:any)=><div className="stat-card" key={label}><div><p>{label}</p><strong>{v??'—'}</strong></div><div className={'stat-icon '+color}><Icon size={23}/></div></div>)}</div>}
export function Bars({items,color='red'}:{items:any[],color?:string}){const max=Math.max(1,...items.map(x=>x.count));return <div className="bars">{items.length?items.map(x=><div className="bar-row" key={x.name}><div><span>{typeNames[x.name]||x.name}</span><strong>{x.count}</strong></div><div className="bar-track"><div className={color} style={{width:100*x.count/max+'%'}}/></div></div>):<Empty/>}</div>}
export function QuestionForm({q,setQ}:{q:Question,setQ:(q:Question)=>void}){const set=(k:string,v:any)=>setQ({...q,[k]:v});return <div className="question-form"><Field label="Nội dung câu hỏi"><textarea rows={3} required minLength={10} value={q.content} onChange={e=>set('content',e.target.value)}/></Field><div className="form-grid"><Field label="Loại câu hỏi"><select value={q.type} onChange={e=>{const t=e.target.value;setQ({...q,type:t,options:t==='SHORT'?[]:t==='TRUE_FALSE'?['Đúng','Sai']:['','','',''],correct:t==='SHORT'?[]:[0]})}}>{Object.entries(typeNames).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></Field><Field label="Mức độ nhận thức"><Select value={q.level} onChange={v=>set('level',v)} items={levels}/></Field></div>{q.type!=='SHORT'&&<div className="options-editor"><p className="muted">Đánh dấu đáp án đúng {q.type==='MULTIPLE'?'(có thể chọn nhiều)':''}</p>{q.options.map((o,i)=><div className="option-edit" key={i}><input aria-label={`Đáp án ${i+1} đúng`} type={q.type==='MULTIPLE'?'checkbox':'radio'} name="correct" checked={q.correct.includes(i)} onChange={()=>set('correct',q.type==='MULTIPLE'?(q.correct.includes(i)?q.correct.filter(v=>v!==i):[...q.correct,i]):[i])}/><span>{String.fromCharCode(65+i)}.</span><input aria-label={`Phương án ${i+1}`} required value={o} onChange={e=>set('options',q.options.map((v,j)=>j===i?e.target.value:v))}/></div>)}</div>}<Field label={q.type==='SHORT'?'Hướng dẫn chấm / Đáp án gợi ý (không bắt buộc)':'Giải thích đáp án (không bắt buộc)'}><textarea placeholder="Có thể để trống" rows={2} value={q.explanation} onChange={e=>set('explanation',e.target.value)}/></Field><div className="form-grid"><Field label="Chủ đề"><input list="topic-list" required value={q.topic} onChange={e=>set('topic',e.target.value)}/><datalist id="topic-list">{topics.map(v=><option key={v}>{v}</option>)}</datalist></Field><Field label="Đối tượng"><Select value={q.audience} onChange={v=>set('audience',v)} items={audiences}/></Field></div><Field label="Nguồn tài liệu / Trích đoạn đối chiếu (không bắt buộc)"><textarea placeholder="Có thể để trống" rows={2} value={q.source} onChange={e=>set('source',e.target.value)}/></Field></div>}
export function QuestionView({q,index,answers=true}:{q:any,index:number,answers?:boolean}){return <article className="question-view"><div className="question-meta"><Badge>Câu {index+1}</Badge><span>{typeNames[q.type]} · {q.level}</span></div><h3>{q.content}</h3>{q.options.map((o:string,i:number)=><div key={i} className={'answer-option '+(answers&&q.correct.includes(i)?'correct':'')}><span>{String.fromCharCode(65+i)}</span>{o}{answers&&q.correct.includes(i)&&<CheckCircle2 size={17}/>}</div>)}{answers&&<div className="explanation"><strong>{q.type==='SHORT'?'Hướng dẫn chấm':'Giải thích'}:</strong> {q.explanation}<small>Nguồn: {q.source}</small></div>}</article>}
export const statusNames:Record<string,string>={DRAFT:'Nháp',PENDING:'Chờ duyệt',APPROVED:'Đã duyệt',REJECTED:'Trả lại'};
export const statusTone:Record<string,string>={DRAFT:'',PENDING:'gold',APPROVED:'green',REJECTED:'red'};
export const StatusBadge=({s}:{s?:string})=>s?<Badge tone={statusTone[s]??''}>{statusNames[s]??s}</Badge>:null;
export const flagLabel:Record<string,string>={QUA_DE:'Quá dễ',QUA_KHO:'Quá khó',KHONG_PHAN_BIET:'Không phân biệt',NGHICH_DAO:'Nghịch đảo — soát lại',LECH_MUC_DO:'Lệch mức độ'};
export function Card({Icon,label,value,color}:{Icon:any,label:string,value:any,color:string}){return <div className="stat-card"><div><p>{label}</p><strong>{value??'—'}</strong></div><div className={'stat-icon '+color}><Icon size={23}/></div></div>}
