import {db} from '../src/db.js';
import bcrypt from 'bcrypt';
const topics=[
['Truyền thống Quân đội nhân dân Việt Nam',[
['Quân đội nhân dân Việt Nam được thành lập vào ngày nào?','22/12/1944','19/8/1945','2/9/1945','30/4/1975','Ngày 22/12/1944 là ngày thành lập Đội Việt Nam Tuyên truyền Giải phóng quân, tiền thân của Quân đội nhân dân Việt Nam.'],
['Tên tổ chức tiền thân của Quân đội nhân dân Việt Nam khi thành lập là gì?','Đội Việt Nam Tuyên truyền Giải phóng quân','Việt Nam Giải phóng quân','Vệ quốc đoàn','Quân đội Quốc gia Việt Nam','Đội Việt Nam Tuyên truyền Giải phóng quân thành lập ngày 22/12/1944.'],
['Hoạt động nào thể hiện việc học tập truyền thống quân đội trong thực tiễn?','Hoàn thành nhiệm vụ, đoàn kết và giúp đỡ nhân dân','Chỉ ghi nhớ các mốc thời gian','Chỉ tham gia khi được khen thưởng','Coi giáo dục truyền thống là việc của giáo viên','Học tập truyền thống cần gắn với trách nhiệm và hành động cụ thể.'],
['Vì sao giáo dục truyền thống cần gắn với nhiệm vụ hiện tại?','Để chuyển nhận thức thành ý thức trách nhiệm và hành động','Để thay thế huấn luyện chuyên môn','Để giảm yêu cầu chấp hành kỷ luật','Để chỉ tập trung vào thành tích quá khứ','Giáo dục truyền thống có ý nghĩa khi giúp quân nhân vận dụng vào thực hiện nhiệm vụ.']]],
['Phẩm chất Bộ đội Cụ Hồ',[
['Hành vi nào thể hiện tinh thần đoàn kết đồng đội?','Chủ động giúp đồng đội khắc phục khó khăn','Che giấu mọi khuyết điểm của nhau','Chỉ giúp người cùng quê','Đùn đẩy nhiệm vụ khó cho người khác','Đoàn kết gắn với giúp đỡ chân thành, trách nhiệm và cùng tiến bộ.'],
['Khi được nhân dân giúp đỡ, quân nhân cần ứng xử thế nào?','Trân trọng, cảm ơn và giữ đúng lễ tiết tác phong','Coi đó là trách nhiệm bắt buộc của người dân','Đòi hỏi thêm lợi ích cá nhân','Tự ý nhận mọi quà tặng có giá trị','Ứng xử lịch sự, tôn trọng nhân dân góp phần giữ gìn hình ảnh Bộ đội Cụ Hồ.'],
['Khi phát hiện bản thân làm sai, cách xử lý phù hợp là gì?','Trung thực nhận trách nhiệm và sửa chữa','Giấu để không ảnh hưởng thành tích','Đổ lỗi cho tập thể','Chỉ nhận lỗi khi có người chứng kiến','Trung thực, tự phê bình và sửa chữa khuyết điểm thể hiện trách nhiệm cá nhân.'],
['Tinh thần tiết kiệm được thể hiện qua việc nào?','Sử dụng điện, nước và vật chất đúng nhu cầu nhiệm vụ','Cắt giảm mọi nhu cầu thiết yếu','Không bảo dưỡng trang bị để tiết kiệm thời gian','Chỉ tiết kiệm khi có kiểm tra','Tiết kiệm là sử dụng hợp lý nguồn lực, không lãng phí và vẫn bảo đảm nhiệm vụ.']]],
['Điều lệnh, điều lệ Quân đội',[
['Khi chưa hiểu rõ nội dung nhiệm vụ được giao, quân nhân nên làm gì?','Báo cáo, đề nghị người giao nhiệm vụ giải thích rõ','Tự suy đoán rồi làm theo ý mình','Bỏ qua nhiệm vụ','Nhờ người khác làm thay mà không báo cáo','Nắm chắc nhiệm vụ giúp tổ chức thực hiện đúng, hạn chế sai sót.'],
['Duy trì lễ tiết, tác phong quân nhân nhằm mục đích gì?','Thể hiện tính tổ chức, kỷ luật và văn hóa ứng xử','Chỉ phục vụ các buổi lễ','Thay thế năng lực chuyên môn','Chỉ để đối phó với kiểm tra','Lễ tiết tác phong phải được duy trì thường xuyên trong sinh hoạt và công tác.'],
['Khi tham gia hoạt động tập thể, yêu cầu phù hợp là gì?','Đúng giờ, đúng thành phần và chấp hành hướng dẫn','Tự ý thay đổi vị trí khi chưa báo cáo','Đến muộn nếu không có kiểm tra','Chỉ tuân thủ khi có cán bộ trực tiếp theo dõi','Chấp hành thời gian và hướng dẫn góp phần bảo đảm thống nhất, chính quy.'],
['Vì sao cần học đi đôi với thực hành điều lệnh?','Để hình thành thói quen và tác phong đúng','Để không cần ôn lại kiến thức','Để thay thế toàn bộ nội dung huấn luyện khác','Để chỉ đạt điểm kiểm tra lý thuyết','Thực hành thường xuyên giúp chuyển kiến thức thành hành vi chuẩn mực.']]],
['Xây dựng chính quy, chấp hành kỷ luật',[
['Khi đồng đội có biểu hiện vi phạm nền nếp, nên làm gì?','Nhắc nhở, giúp đỡ và báo cáo đúng trách nhiệm','Cổ vũ vì cho rằng không nghiêm trọng','Phát tán hình ảnh để chế giễu','Bỏ qua vì không liên quan bản thân','Giúp đồng đội nhận rõ và sửa sai, xử lý theo trách nhiệm, tránh làm tổn thương danh dự.'],
['Biện pháp nào góp phần duy trì nền nếp bền vững?','Kết hợp giáo dục, nêu gương và kiểm tra thường xuyên','Chỉ kiểm tra đột xuất vào cuối tháng','Chỉ yêu cầu học viên thực hiện','Đợi có vi phạm mới phổ biến quy định','Duy trì nền nếp cần tính thường xuyên và trách nhiệm nêu gương.'],
['Khi có nguy cơ mất an toàn trong hoạt động, cần làm gì?','Cảnh báo, báo cáo và thực hiện biện pháp an toàn theo hướng dẫn','Tiếp tục để hoàn thành nhanh','Che giấu vì sợ bị nhắc nhở','Tự ý xử lý vượt khả năng','Phát hiện sớm, báo cáo và thực hiện đúng quy trình giúp phòng ngừa sự cố.'],
['Tự giác chấp hành kỷ luật được hiểu thế nào?','Thực hiện đúng yêu cầu kể cả khi không có người giám sát','Chỉ thực hiện khi có kiểm tra','Lựa chọn quy định thuận tiện để thực hiện','Chỉ thực hiện khi có phần thưởng','Tính tự giác thể hiện ở hành vi ổn định, có trách nhiệm trong mọi hoàn cảnh.']]],
['Bảo vệ nền tảng tư tưởng của Đảng',[
['Khi gặp thông tin chưa được kiểm chứng trên mạng, cần làm gì?','Kiểm tra nguồn và chưa chia sẻ khi chưa xác minh','Chia sẻ ngay để nhiều người biết','Coi nhiều lượt thích là bằng chứng đúng','Chỉ đọc tiêu đề rồi kết luận','Kiểm chứng nguồn, thời điểm và ngữ cảnh giúp tránh lan truyền thông tin sai.'],
['Nguồn nào nên được ưu tiên khi nghiên cứu một văn kiện?','Bản văn kiện chính thức và tài liệu học tập được phê duyệt','Ảnh cắt rời không rõ xuất xứ','Bài đăng ẩn danh','Bình luận trên mạng không dẫn nguồn','Nguồn chính thức giúp đối chiếu chính xác nội dung và tránh trích dẫn sai.'],
['Khi trao đổi về nội dung có ý kiến khác nhau, nên chọn cách nào?','Lập luận có căn cứ, tôn trọng người trao đổi','Công kích cá nhân','Cắt ghép lời nói của người khác','Dùng tin chưa kiểm chứng để phản bác','Trao đổi cần dựa trên chứng cứ và thái độ văn minh, tránh công kích cá nhân.'],
['Vì sao cần đọc đầy đủ ngữ cảnh khi trích dẫn tài liệu?','Để hiểu đúng ý nghĩa và tránh diễn giải sai','Để chỉ chọn phần phù hợp ý mình','Để không cần ghi nguồn','Để có thể sửa nội dung trích dẫn','Đọc đầy đủ ngữ cảnh giúp bảo đảm tính chính xác và trung thực khi sử dụng tài liệu.']]]
] as const;
async function main(){for(const [username,name,role] of [['admin','Quản trị viên','ADMIN'],['giaovien','Giáo viên demo','TEACHER'],['hocvien','Học viên demo','STUDENT']])await db.user.upsert({where:{username},update:{},create:{username,name,role,password:await bcrypt.hash('123456',12)}});const classroom=await db.classroom.upsert({where:{name:'Lớp mẫu – Khóa 1'},update:{},create:{name:'Lớp mẫu – Khóa 1',note:'Lớp trình diễn, có thể đổi tên hoặc xóa trong Quản trị.'}});
await db.user.updateMany({where:{username:'hocvien',classroomId:null},data:{classroomId:classroom.id}});
if(await db.question.count())return;const teacher=await db.user.findUniqueOrThrow({where:{username:'giaovien'}});const levels=['Nhận biết','Thông hiểu','Vận dụng','Vận dụng cao'];for(const [topic,items] of topics){for(let i=0;i<items.length;i++){const [content,...a]=items[i];await db.question.create({data:{content,type:'SINGLE',options:JSON.stringify(a.slice(0,4)),correct:'[0]',explanation:a[4],topic,level:levels[i],audience:'Học viên',source:'Dữ liệu minh họa giáo dục chính trị, biên soạn phục vụ demo; giáo viên đối chiếu tài liệu được phê duyệt trước khi sử dụng chính thức.',creatorId:teacher.id}});}const fact=items[2];for(const type of ['TRUE_FALSE','MULTIPLE','SHORT'])await db.question.create({data:{content:type==='SHORT'?`Nêu cách vận dụng nội dung “${fact[0]}” vào nhiệm vụ của bản thân và giải thích. 實`.replace(' 實',''):type==='TRUE_FALSE'?`Nhận định sau đúng hay sai: ${fact[1]}.`:`Chọn tất cả hành động phù hợp khi học tập chủ đề “${topic}”.`,type,options:JSON.stringify(type==='SHORT'?[]:type==='TRUE_FALSE'?['Đúng','Sai']:['Học tập tài liệu được phê duyệt','Liên hệ trách nhiệm bản thân','Chia sẻ thông tin chưa kiểm chứng','Chỉ học để đối phó kiểm tra']),correct:JSON.stringify(type==='SHORT'?[]:type==='TRUE_FALSE'?[0]:[0,1]),explanation:type==='SHORT'?`Hướng dẫn chấm: nêu cách làm phù hợp (0,5), giải thích và liên hệ trách nhiệm cụ thể (0,5). ${fact[5]}`:type==='TRUE_FALSE'?fact[5]:'Học tập cần dựa trên tài liệu đúng và gắn với trách nhiệm; không chia sẻ tin chưa kiểm chứng hoặc học đối phó.',topic,level:type==='SHORT'?'Vận dụng cao':'Thông hiểu',audience:'Học viên',source:'Tình huống minh họa phục vụ demo; cần giáo viên thẩm định.',creatorId:teacher.id}});}
const rows=await db.question.findMany({take:10});await db.exam.create({data:{name:'Kiểm tra nhận thức chính trị – Bài mẫu',topic:'Tổng hợp',audience:'Học viên',duration:20,passScore:5,questions:JSON.stringify(rows.map(q=>({...q,options:JSON.parse(q.options),correct:JSON.parse(q.correct)}))),ratios:'[25,25,25,25]',published:true,creatorId:teacher.id}});console.log('Da tao 3 tai khoan, 35 cau hoi, 1 de demo.');}
main().finally(()=>db.$disconnect());
